language: go

go:
  - "1.8"
  - "1.9"
  - "1.10"
  - master

install:
  - go get github.com/golang/protobuf/proto
  - go get github.com/golang/protobuf/protoc-gen-go
  - make proto
  - go get -t ./...

script:
  - make test
